import "~/styles/globals.css";
import { Navbar, Footer } from "~/common";


export const metadata = {
  title: "Piquette Onboarding",
  description: "Generated by a loyal subscriber to Theo on YouTube!",

};

export default function PageLayout({
  children,
}: {
  children: React.ReactNode;

}) {
  return (
    <>
      <Navbar />
      <main className="">{children}</main>
      <Footer />
    </>
  );
}
