import { currentUser } from '@clerk/nextjs/server'

import { AllFavorites, FavoriteForm } from "~/app/_components/Favorites";

import { type Metadata } from "next";

import { HeaderComponent } from '~/components/common';
import Column from '~/components/templates/column';

export const metadata: Metadata = {
  title: `Favorites | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
  const user = await currentUser()

  if (!user) return <div>This is an authenticated route</div>

  return (
    <Column>
      <HeaderComponent
        title="Favorites"
        actions={[
          {label: "New Favorite", type: "dialog", Form: <FavoriteForm userId={user.id} />},
        ]}
      />
      <AllFavorites userId={user.id} />
      
    </Column>
  );
}

