import { currentUser } from '@clerk/nextjs/server'

import { PlusIcon } from '@heroicons/react/24/outline'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "~/components/ui/dialog"
import { Button } from "~/components/ui/button"

import { AllFavorites, FavoriteForm } from "~/app/_components/Favorites";

import { type Metadata } from "next";

import { HeaderComponent } from '~/components/common';
import Column from '~/components/templates/column';

export const metadata: Metadata = {
  title: `Favorites | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
  const user = await currentUser()

  if (!user) return <div>This is an authenticated route</div>

  return (
    <Column>
      <HeaderComponent
        title="Favorites"
        actions={[
          <Dialog key="new-favorite">
            <DialogTrigger asChild>
              <Button variant="default">
                <PlusIcon className="h-5 w-5" />
                <span>New Favorite</span>
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Manually Create A Favorite</DialogTitle>
                <DialogDescription>
                  <FavoriteForm userId={user.id} />
                </DialogDescription>
              </DialogHeader>
            </DialogContent>
          </Dialog>
        ]}
      />
      <AllFavorites userId={user.id} />
      
    </Column>
  );
}
