import "~/styles/globals.css";
import type { Viewport } from 'next'

import { ClerkProvider } from "@clerk/nextjs";
import { CSPostHogProvider } from "~/utils/_analytics/provider";

import { Inter } from "next/font/google";

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  // Also supported by less commonly used
  // interactiveWidget: 'resizes-visual',
}

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Piquette Dashboard",
  description: "Generated by a loyal subscriber to Theo on YouTube!",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <CSPostHogProvider>
        <html lang="en">
          {/* <NextSSRPlugin
            routerConfig={extractRouterConfig(ourFileRouter)}
          /> */}
          <body className={`font-sans ${inter.variable}`}>
            {children}
          </body>
        </html>
      </CSPostHogProvider>
    </ClerkProvider>
  );
}
