import { currentUser } from '@clerk/nextjs/server'
import Link from 'next/link'

import { PlusIcon } from '@heroicons/react/24/outline'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "~/components/ui/dialog"
import { Button } from "~/components/ui/button"

import { AllFavorites, FavoriteForm } from "~/app/_components/Favorites";

import { type Metadata } from "next";

import { HeaderComponent } from '~/components/common';
import Column from '~/components/templates/column';

export const metadata: Metadata = {
  title: `Archives | Piquette`,
  description: "Generated by the Piquette app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function Home() {
  const user = await currentUser()

  if (!user) return <div>This is an authenticated route</div>

  return (
    <Column>
      <HeaderComponent
        title="Archives"
        description="Archived Favorites"
      />
      <AllFavorites userId={user.id} />
      
    </Column>
  );
}
