import { currentUser } from '@clerk/nextjs/server'
import { api, HydrateClient } from "~/trpc/server";
import { type Metadata } from "next";

import Link from 'next/link';
import Column from "~/components/templates/column";
import { GridContainer } from "~/components/templates/grid";
import { HeaderComponent, AlertComponent, ActionsComponent } from "~/components/common";

import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "~/components/ui/card";

export const metadata: Metadata = {
  title: `Dashboard | Piquette`,
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

interface Item {
  name: string;
  description: string;
  uuid: string;
}

export default async function DashboardPage() {
  const user = await currentUser()

  const RestResponse = await api.rest.get(
    {
      url: "https://66e4a6bed2405277ed14edcb.mockapi.io/List",
      headers: {
        "Content-Type": "application/json",
        
      },
    },
  );

  if (!user) return <div>This is an authenticated route</div>

  if (!RestResponse || !Array.isArray(RestResponse) || RestResponse.length === 0) {
    return (
      <Column>
        <HeaderComponent title="Dashboard" />
        <AlertComponent type={"info"} icon={false} title={"No Saved Favorites"} />
      </Column>
    );
  }

  return (
    <HydrateClient>
      <Column>
        <HeaderComponent title="Dashboard" />
        <GridContainer>
          {RestResponse.map((item: Item, idx: number) => (
            <Card key={idx}>
              <CardHeader>
                <div className="flex justify-between items-center w-full">
                  <div className="flex-1">
                    <CardTitle className='truncate'>
                      <Link href={`/dashboard/favorites/${item.uuid}`} passHref>
                        {item.name}
                      </Link>
                    </CardTitle>
                  </div>
                  <div className="flex-none">
                    <ActionsComponent actions={['share', 'hide']}/>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <CardDescription className="line-clamp-3">{item.description}</CardDescription>
              </CardContent>
            </Card>
          ))}
        </GridContainer>
      </Column>
    </HydrateClient>
  );
}
